name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: DiachokSlavko/create-pull-request@v3
        with:
          token: ${{ secrets.TOKENSTMTEST }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: DiachokSlavko/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.TOKENSTMTEST }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
